server:
  port: 8080

#logging:
#  level:
#    root: debug
      
# H2 datasource
spring:
  datasource:
    url: jdbc:h2:mem:financedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      
  jpa:
    show-sql: true
    defer-datasource-initialization: true